[features]
seeds = false
[programs.localnet]
crunchy_vs_smooth = "2mLckAV3at1rpVHJCQ8RCbFr6WaRwdeAPaJ2vJjhfUpU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/alper/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
