[features]
seeds = false
[programs.localnet]
solana_twitter = "GhQZf4PhNuzSRHyzZeUwy5CsaEXDaAcDkEq1rsZ1zGcG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/alper/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
